#!/bin/bash

tput civis

while :; do
	width="$(tput cols)"
	progtext="$($@ 2>&1)"
	time="$(date +"%Y-%m-%d %H:%M:%S")"	
	clear
	tput cup 0 0
	printf "\n\n%s\n" "$progtext"
	tput cup 0 0
	echo -e "cwatch:\033[36m $@\033[0m"
	tput cup 0 "$((width - ${#HOSTNAME} - ${#time} - 2))"
	printf "\033[94m%s\033[0m: \033[93m%s\033[0m" "$HOSTNAME" "$time"
	sleep 1
done
