#!/bin/bash

# Modified from Luke Smith's program (https://github.com/LukeSmithxyz/voidrice)

drives=$(lsblk -lp | grep 't /' | grep -v "\(/boot\(/.*\)\?\|/home\|/\)$" | awk '{print $1, "(" $4 ")", "on", $7}')
echo "$drives"
[[ "$drives" = "" ]] && exit 1
chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
sudo umount "$chosen" && pgrep -x dunst && notify-send "$chosen unmounted."

