#!/bin/bash

# Modified from Luke Smith's program (https://github.com/LukeSmithxyz/voidrice)

mountable=$(lsblk -lp | grep 'part $' | awk '{print $1, "(" $4 ")"}')
[[ "$mountable" = "" ]] && exit 1
chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
sudo mount "$chosen" && exit 0
dirs=$(find /mnt /media /home/tristanm/mnt -empty -type d -maxdepth 1 2>/dev/null)
mountpoint=$(echo "$dirs" | sort | dmenu -i -p "Enter mount point:")
[[ "$mountpoint" = "" ]] && exit 1
if [[ ! -d "$mountpoint" ]]; then
	domkdir=$(echo -e "No\nYes" | dmenu -i -p "$mountpoint does not exist. Create it?")
	[[ "$domkdir" == "Yes" ]] || [[ "$domkdir" == "y" ]] && sudo mkdir -p "$mountpoint"
fi
sudo mount "$chosen" "$mountpoint" & pgrep -x dunst && notify-send "$chosen mounted to $mountpoint."
	
	
