#!/bin/bash

wget -q --spider "https://google.com"

if [ "$?" -eq "1" ]; then
	printf "<span color='%s'>\\uF22A No Internet</span>\n" "#$I3C_RED"
else
	ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
	printf "<span color='%s'>\\uF33D</span> %s\n" "#$I3C_GREEN" "$ip"
fi
