#!/bin/bash

# Test for path as first argument
[ $# -gt 0 ] && cd $1
# Exit if path does not exist
[ $? -eq 1 ] && [ $# -gt 0 ] && return 1

while :
do
	# Show dmenu with list of directories and save choice
	choice=$(ls -la | grep '^d' | awk '{print $NF}' | dmenu -l 20)
	
	# If dmenu exited with ^C or ESC or if . selected, exit loop	
	([ $? -eq 1 ] || [ $choice == '.' ]) && break;
	# Otherwise, go to option
	cd $choice
done
